defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

path: /srv/beegfs/scratch/groups/rodem/jetssl/jetssl_finetune/
plot_dir: plots/
outfile: test

models:
  a: vertexer_600000
