defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

path: /srv/beegfs/scratch/groups/rodem/jetssl/jetssl_finetune_paper/
plot_dir: plots/
outfile: test

models: {}
  # a: trk_diff
  # b: trk_flow
  # c: trk_kmeans
  # d: trk_reg
  # e: trk_untrained
  # f: trk_vae
  # g: tracker

