defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

path: /srv/beegfs/scratch/groups/rodem/flowbert/single_epoch_pretrain
plot_dir: /home/users/l/leighm/DiffBEIT/plots
outfile: jetclass

models:
  a: finetune_flow_10
  b: finetune_flow_6
  c: finetune_kmeans_256
  d: finetune_kmeans_512
  e: finetune_kmeans_768
  f: finetune_clr
  g: reinit_kmeans_768
