defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

path: /srv/beegfs/scratch/groups/rodem/jetssl/jetssl_finetune_paper2/
plot_dir: plots/
outfile: test

models:
  a: jetclass_diff
  b: jetclass_mdm
  c: jetclass_flow
  d: jetclass_reg
  e: jetclass_gpt
  f: jetclass_vae
  g: jetclass_kmeans

