# Need to be a dictionary itself to run with python train.py +model/tasks=kmeans
kmeans:
  _target_: src.models.mpm_tasks.KmeansTask
  _partial_: True

  weight: 1.0
  detach: False
  apply_every: 1
  id_conditional: False
  id_embed_dim: 64

  kmeans_path: ${paths.root_dir}/resources/kmeans_7.pkl
  use_weights: False
