build_docker: &build_docker
  stage: build
  needs: []
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  variables:
    IMAGE_DESTINATION: $CI_REGISTRY_IMAGE:latest
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $IMAGE_DESTINATION
    - echo "Image pushed successfully to ${IMAGE_DESTINATION}"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
