variables:
  TEST_CMD: pytest --show-capture=stdout

.test-template: &test-template
  stage: tests
  image: $CI_REGISTRY_IMAGE:latest
  rules:
    - changes: ["pyproject.toml", "requirements.txt", "jetssl/**/*.py", "**/*.yaml"]

unit-tests:
  <<: *test-template
  script:
    - $TEST_CMD tests/test_mpm.py
