_target_: src.models.classifier.Classifier

backbone_path: /srv/beegfs/scratch/groups/rodem/jetssl/jetssl2/backbones/diff.pkl

defaults:
  - optimizer: default.yaml
  - scheduler: cosine.yaml
  - class_head: ca.yaml
  - _self_
