_target_: src.models.classifier.Classifier

backbone_path: /srv/beegfs/scratch/groups/rodem/jetssl/jetssl_fixed/backbones/no_backbone.pkl

defaults:
  - optimizer: default.yaml
  - scheduler: cosine.yaml
  - class_head: linear.yaml
  - _self_
