_target_: src.models.gpt.JetGPT

vae_path: /home/users/l/leighm/jetssl/resources/vqvae.pkl

defaults:
  - encoder_config: small.yaml
  - optimizer: default.yaml
  - scheduler: warmup_decay.yaml
  - class_head: ca.yaml
  - _self_
