_target_: src.models.classifier.Classifier

backbone_path: /srv/beegfs/scratch/groups/rodem/jetssl/jetssl/reg/backbone.pkl
reinstantiate: False

defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: warmup.yaml
  - class_head: ca.yaml
