_target_: src.models.jetdino.JetDINO

t_temp: 0.05
s_temp: 0.1
t_ema: 0.995
c_ema: 0.9

defaults:
  - _self_
  - encoder_config: small.yaml
  - optimizer: default.yaml
  - scheduler: warmup.yaml
  - class_head: ca.yaml
