_target_: src.models.mdm.MaskedDiffusionModelling

time_dim: 32

decoder_config:
  do_output_linear: True
  do_input_linear: True

defaults:
  - encoder_config: small.yaml
  - decoder_config: small.yaml
  - optimizer: default.yaml
  - scheduler: cosine.yaml
  - class_head: ca.yaml
  - _self_
