_target_: src.models.mpm.MaskedParticleModelling

use_id: True
do_mae: True
tasks: {}

defaults:
  - encoder_config: small.yaml
  - decoder_config: small.yaml
  - optimizer: default.yaml
  - scheduler: cosine.yaml
  - _self_
