_target_: src.models.mpm.MaskedParticleModelling

use_id: True
objective: mae
use_hlv: False
tasks: {}

defaults:
  - encoder_config: small.yaml
  - decoder_config: small.yaml
  - optimizer: default.yaml
  - scheduler: warmup_decay.yaml
  - _self_
