_target_: src.models.mpm_diff.MPMDiff

id_weight: 0.0
cst_weight: 1.0

embed_dim: 128

diff_config:
  time_dim: 16
  mlp_config:
    num_blocks: 3
    hddn_dim: 128
    act_h: SiLU
    norm: LayerNorm
    do_res: True
    init_zeros: True

defaults:
  - _self_
  - encoder_config: small.yaml
  - decoder_config: small.yaml
  - optimizer: default.yaml
  - scheduler: warmup.yaml
  - class_head: ca.yaml
