_target_: src.models.mpm_flow.MPMFlow

id_weight: 0.0
cst_weight: 1.0

embed_dim: 128

defaults:
  - _self_
  - encoder_config: small.yaml
  - decoder_config: small.yaml
  - optimizer: default.yaml
  - scheduler: warmup.yaml
  - class_head: ca.yaml
  - flow_config: default.yaml
