_target_: src.models.mpm_flow.MPMFlow

embed_dim: 64

defaults:
  - _self_
  - encoder_config: small.yaml
  - decoder_config: small.yaml
  - optimizer: default.yaml
  - scheduler: warmup.yaml
  - class_head: ca.yaml
  - flow_config: default.yaml
