_target_: src.models.mpm_token.MPMKmeans

id_weight: 0.0
cst_weight: 1.0

kmeans_config:
  n_clusters: 8192
  max_iter: 500
  verbose: 10

defaults:
  - _self_
  - encoder_config: small.yaml
  - decoder_config: small.yaml
  - optimizer: default.yaml
  - scheduler: warmup.yaml
  - class_head: ca.yaml
