_target_: src.models.mpm_base.MPMBase

id_weight: 1.0
cst_weight: 0.0

defaults:
  - _self_
  - encoder_config: small.yaml
  - decoder_config: small.yaml
  - optimizer: default.yaml
  - scheduler: warmup.yaml
  - class_head: ca.yaml
