_target_: src.models.sdm.MaskedDiffusionModelling

time_dim: 32

ctxt_config:
  hddn_dim: 64
  num_blocks: 2
  outp_dim: 8
  norm: LayerNorm

optimizer:
  lr: 1.0e-4

decoder_config:
  do_output_linear: True
  do_input_linear: True
  num_layers: 6

defaults:
  - encoder_config: small.yaml
  - decoder_config: small.yaml
  - optimizer: default.yaml
  - scheduler: warmup.yaml
  - class_head: linear.yaml
  - _self_
