_target_: src.models.tracker.Tracker

backbone_path: /srv/beegfs/scratch/groups/rodem/jetssl/jetssl2/backbones/kmeans.pkl

mlp_config:
  num_blocks: 2
  hddn_dim: 128
  dropout: 0.2
  norm: LayerNorm

class_weights: [0.3878, 1.4245, 3.3344, 2.3857]

defaults:
  - optimizer: default.yaml
  - scheduler: cosine.yaml
  - _self_
