_target_: src.models.vertexer.Vertexer

backbone_path: /srv/beegfs/scratch/groups/rodem/jetssl/jetssl2/backbones/kmeans.pkl
pos_weight: 0.7825 # Calculated from shlomi ratio

vertex_config:
  num_blocks: 3
  hddn_dim: 256
  dropout: 0.2
  norm: LayerNorm

defaults:
  - optimizer: default.yaml
  - scheduler: cosine.yaml
  - _self_
