# output dir will be created by hydra
data_dir: /srv/fast/share/rodem/
output_dir: /srv/beegfs/scratch/groups/rodem/jetssl/

# Interpolated
root_dir: ${oc.env:PROJECT_ROOT}
full_path: ${paths.output_dir}/${project_name}/${network_name}/
