defaults:
  - shared/btag@train_set
  - shared/btag@val_set
  - shared/btag@test_set

_target_: src.datamodules.hdf.JetDataModule

train_set:
  processes: train

val_set:
  processes: valid

test_set:
  processes: test

loader_config:
  batch_size: 500
  num_workers: 2
  drop_last: true
  shuffle: true
  collate_fn:
    _target_: src.datamodules.preprocessing.batch_preprocess
    _partial_: true
    fn:
      _target_: joblib.load
      filename: ${paths.root_dir}/resources/cst_quant.joblib
