defaults:
  - jetclass

transforms:
  - _target_: src.datamodules.preprocessing.batch_masking
    _partial_: true
    fn:
      _target_: src.datamodules.masking.random_uniform_masking
      _partial_: true
  - _target_: src.datamodules.preprocessing.preprocess
    _partial_: true
    fn:
      _target_: joblib.load
      filename: ${paths.root_dir}/resources/cst_quant.joblib
    get_ratios: True
    # hlv_fn:
    #   _target_: joblib.load
    #   filename: ${paths.root_dir}/resources/jet_quant.joblib

# Mask Fraction Performance
# 0.1 -> 0.8186
# 0.2 -> 0.8295
# 0.3 -> 0.8297
# 0.4 -> 0.8261
# 0.5 -> 0.8217
# 0.6 -> 0.8193
# 0.7 -> 0.8184
# 0.8 -> 0.8028
# 0.9 -> 0.7825
