defaults:
  - jetclass_base/mappartial@train_set
  - jetclass_base/mappable@val_set
  - jetclass_base/mappable@test_set
  - jet_transforms/mpm@train_set.transforms
  - jet_transforms/mpm@val_set.transforms
  - jet_transforms/mpm@test_set.transforms

_target_: src.datamodules.hdf.JetDataModule

train_set:
  path: ${paths.data_dir}/JetClassH5/train_100M/

val_set:
  path: ${paths.data_dir}/JetClassH5/val_5M/
  n_files: 1 # Really dont need 5 million validation events

test_set:
  path: ${paths.data_dir}/JetClassH5/test_20M/

loader_config:
  batch_size: 1000
  num_workers: 3 # Speed testing show that 3 workers is enough even with augs
  drop_last: false
  shuffle: true
  collate_fn:
    _target_: src.datamodules.collation.batch_preprocess_impact
    _partial_: true
    fn:
      _target_: joblib.load
      filename: ${paths.root_dir}/src/datamodules/impact_processor.joblib
