defaults:
  - shared/stream@train_set
  - shared/stream@val_set
  - shared/stream@test_set

_target_: src.datamodules.hdf_stream.StreamModule

train_set:
  path: ${paths.data_dir}/JetClassH5/train_100M_combined.h5

val_set:
  path: ${paths.data_dir}/JetClassH5/val_5M_combined.h5
  n_jets: 1000_000 # Really dont need 5M

test_set:
  path: ${paths.data_dir}/JetClassH5/test_20M_combined.h5
  n_jets: 2000_000 # Really dont need 20M

num_workers: 2 # Keep having issues with num_workers > 1 :(
batch_size: 1000
pin_memory: True
transforms:
  - _target_: src.datamodules.preprocessing.preprocess
    _partial_: true
    fn:
      _target_: joblib.load
      filename: ${paths.root_dir}/resources/cst_quant.joblib
