defaults:
  - jetclass_base/cwola@train_set # We use mappable datasets
  - jetclass_base/cwola@val_set
  - jetclass_base/cwola@test_set
  - jet_transforms/standard@train_set.transforms
  - jet_transforms/standard@val_set.transforms
  - jet_transforms/standard@test_set.transforms

_target_: src.datamodules.hdf.JetDataModule

train_set:
  path: ${paths.data_dir}/JetClassH5/train_100M/

val_set:
  path: ${paths.data_dir}/JetClassH5/val_5M/

test_set:
  path: ${paths.data_dir}/JetClassH5/test_20M/

loader_config:
  batch_size: 500
  num_workers: 2
  drop_last: true
  shuffle: true
  collate_fn:
    _target_: src.datamodules.preprocessing.batch_preprocess
    _partial_: true
    fn:
      _target_: joblib.load
      filename: ${paths.root_dir}/resources/preprocessor_all.joblib
