_target_: src.datamodules.hdf_stream.StreamModule

train_set:
  _target_: src.datamodules.hdf_stream.JetHDFStream
  _partial_: True
  path: ${paths.data_dir}/JetClassH5/train_100M_combined.h5
  n_classes: 10

val_set:
  _target_: src.datamodules.hdf_stream.JetHDFStream
  _partial_: True
  path: ${paths.data_dir}/JetClassH5/val_5M_combined.h5
  n_classes: 10
  n_jets: 1000_000 # Dont need 5M

test_set:
  _target_: src.datamodules.hdf_stream.JetHDFStream
  _partial_: True
  path: ${paths.data_dir}/JetClassH5/test_20M_combined.h5
  n_classes: 10
  n_jets: 1000_000 # Dont need 20M

num_workers: 10
batch_size: 1000
pin_memory: True
transforms:
  - _target_: src.datamodules.preprocessing.batch_masking
    _partial_: true
    fn:
      _target_: src.datamodules.masking.random_masking
      _partial_: true
      mask_fraction: 0.3
  - _target_: src.datamodules.preprocessing.preprocess
    _partial_: true
    fn:
      _target_: joblib.load
      filename: ${paths.root_dir}/resources/cst_quant.joblib
    hlv_fn:
      _target_: joblib.load
      filename: ${paths.root_dir}/resources/jet_quant.joblib

# Mask Fraction Performance
# 0.1 -> 0.8186
# 0.2 -> 0.8295
# 0.3 -> 0.8297
# 0.4 -> 0.8261
# 0.5 -> 0.8217
# 0.6 -> 0.8193
# 0.7 -> 0.8184
# 0.8 -> 0.8028
# 0.9 -> 0.7825
