_target_: src.datamodules.hdf_stream.StreamModule

train_set:
  path: ${paths.data_dir}/JetClassH5/train_100M_combined.h5

val_set:
  path: ${paths.data_dir}/JetClassH5/val_5M_combined.h5
  n_jets: 1000_000 # Dont need 5M

test_set:
  path: ${paths.data_dir}/JetClassH5/test_20M_combined.h5
  n_jets: 1000_000 # Dont need 20M

num_workers: 6
batch_size: 1000
pin_memory:
transforms:
  - _target_: src.datamodules.preprocessing.batch_masking
    _partial_: true
    fn:
      _target_: src.datamodules.masking.random_masking
      _partial_: true
  - _target_: src.datamodules.preprocessing.preprocess
    _partial_: true
    fn:
      _target_: joblib.load
      filename: ${paths.root_dir}/resources/preprocessor_all.joblib
