defaults:
  - shlomi_base/mappable@train_set
  - shlomi_base/mappable@val_set
  - shlomi_base/mappable@test_set
  - jet_transforms/standard@train_set.transforms
  - jet_transforms/standard@val_set.transforms
  - jet_transforms/standard@test_set.transforms

_target_: src.datamodules.hdf.JetDataModule

train_set:
  processes: training

val_set:
  processes: valid

test_set:
  processes: test

loader_config:
  batch_size: 512
  num_workers: 2
  drop_last: true
  shuffle: true
  collate_fn:
    _target_: src.datamodules.collation.batch_preprocess_impact
    _partial_: true
    fn:
      _target_: joblib.load
      filename: ${paths.root_dir}/src/datamodules/impact_processor.joblib
