_target_: src.datamodules.hdf.JetDataModule

train_set:
  _target_: src.datamodules.hdf.JetMappable
  _partial_: True
  path: &path ${paths.data_dir}/TopTagging
  processes: train
  n_classes: &n_classes 2
  features: &feats
  - [csts, f, [128]]
  - [mask, bool, [128]]
  - [jets, f, null]
  - [labels, l, null]
  - [csts_id, l, [128]]

val_set:
  _target_: src.datamodules.hdf.JetMappable
  _partial_: True
  path: *path
  processes: val
  n_classes: *n_classes
  features: *feats

test_set:
  _target_: src.datamodules.hdf.JetMappable
  _partial_: True
  path: *path
  processes: test
  n_classes: *n_classes
  features: *feats

loader_config:
  batch_size: 512
  num_workers: 2
  drop_last: true
  shuffle: true
  collate_fn:
    _target_: src.datamodules.preprocessing.batch_preprocess
    _partial_: true
    fn:
      _target_: joblib.load
      filename: ${paths.root_dir}/resources/preprocessor_all.joblib
