verbose: false
printshellcmds: true
jobs: 200 # Maximum number of jobs to run in parallel

executor: slurm
default-resources:
  slurm_account: golling
  slurm_partition: shared-cpu,private-dpnc-cpu
  runtime: 60 # minutes
  mem_mb: 4000
  threads: 12
sdm: apptainer
apptainer-args: >- # multi-line string
  --nv
  --bind /srv,/home
  --cleanenv
  --env PYTHONPATH=.
  --env WANDB_API_KEY=$WANDB_API_KEY
