_target_: src.datamodules.transforms.compose
_partial_: True
transforms:
  - _target_: src.datamodules.transforms.apply_masking
    _partial_: True
    masking_fn:
      _target_: src.datamodules.masking.random_masking
      _partial_: True
      mask_fraction: 0.5
    key: null_mask
  - _target_: src.datamodules.transforms.apply_masking
    _partial_: True
    masking_fn:
      _target_: src.datamodules.masking.random_masking
      _partial_: True
      mask_fraction: 0.2
    key: target_mask
