min_sigma: 1.0e-5
max_sigma: 80
p_mean: -1.2
p_std: 1.2
cosine_config:
  encoding_dim: 16
  scheme: exponential
unet_config:
  min_size: 4
  attn_below: 0
  start_channels: 16
  max_channels: 64
  zero_out: True
  n_blocks_per_layer: 1
  use_ctxt_embedder: False
  resnet_config:
    act: silu
    nrm_groups: 4

sampler_function:
  _target_: mltools.mltools.diffusion.sample_heun
  _partial_: True

sigma_function:
  _target_: mltools.mltools.diffusion.get_sigmas_karras
  _partial_: True
  n_steps: 50
  rho: 7
